//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alabama_GridAlabama_RegionData
    {
        public int RIO { get; set; }
        public string RIO_DESC { get; set; }
        public Nullable<double> IncomeTotal { get; set; }
        public Nullable<double> EmploymentTotal { get; set; }
        public Nullable<double> GDPTotal { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> Supply { get; set; }
        public Nullable<double> Demand { get; set; }
        public Nullable<double> FederalGenTotal { get; set; }
        public Nullable<double> StateTotal { get; set; }
        public Nullable<double> LocalTotal { get; set; }
    }
}
