//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlabamaRest_GridRegionValues
    {
        public Nullable<int> RIO { get; set; }
        public string RIO_DESC { get; set; }
        public Nullable<double> Inc { get; set; }
        public Nullable<double> Emp { get; set; }
        public Nullable<double> GDP { get; set; }
        public Nullable<double> FederalGen { get; set; }
        public Nullable<double> State { get; set; }
        public Nullable<double> Local { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<short> Locked { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
