//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultData
    {
        public int RIO { get; set; }
        public Nullable<int> RIO_KEY { get; set; }
        public Nullable<int> REGION_ID { get; set; }
        public Nullable<double> Inc { get; set; }
        public Nullable<double> Emp { get; set; }
        public Nullable<double> GDP { get; set; }
        public Nullable<double> Wages { get; set; }
        public Nullable<double> P { get; set; }
        public Nullable<double> FederalGen { get; set; }
        public Nullable<double> FederalIns { get; set; }
        public Nullable<double> State { get; set; }
        public Nullable<double> Local { get; set; }
        public Nullable<double> Supply { get; set; }
        public Nullable<double> Demand { get; set; }
        public Nullable<double> IncomeTotal { get; set; }
        public Nullable<double> EmploymentTotal { get; set; }
        public Nullable<double> GDPTotal { get; set; }
        public Nullable<double> LocalTotal { get; set; }
        public Nullable<double> StateTotal { get; set; }
        public Nullable<double> FederalGenTotal { get; set; }
        public Nullable<short> Locked { get; set; }
    }
}
