//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInfo
    {
        public Nullable<double> DollarsPerFTE { get; set; }
        public Nullable<double> DollarsPerPD { get; set; }
        public Nullable<double> DollarsPerCN { get; set; }
        public Nullable<double> DollarsPerLN { get; set; }
        public Nullable<double> DollarsPerFN { get; set; }
        public Nullable<double> PercentCamping { get; set; }
        public Nullable<double> PercentLodging { get; set; }
        public Nullable<double> PercentFriends { get; set; }
        public Nullable<double> C0 { get; set; }
        public Nullable<double> C1 { get; set; }
        public Nullable<double> C2 { get; set; }
        public Nullable<double> C3 { get; set; }
        public Nullable<double> C4 { get; set; }
        public Nullable<double> C5 { get; set; }
        public Nullable<double> C6 { get; set; }
        public Nullable<double> C7 { get; set; }
        public Nullable<double> C8 { get; set; }
        public Nullable<double> C9 { get; set; }
        public Nullable<double> C10 { get; set; }
        public Nullable<double> C11 { get; set; }
        public Nullable<double> C12 { get; set; }
        public Nullable<double> C13 { get; set; }
        public Nullable<double> C14 { get; set; }
        public Nullable<double> C15 { get; set; }
        public Nullable<double> C16 { get; set; }
        public Nullable<double> C17 { get; set; }
        public Nullable<double> visitors { get; set; }
        public Nullable<double> capital { get; set; }
        public Nullable<double> rest { get; set; }
        public Nullable<double> RCRatio { get; set; }
        public Nullable<double> RVRatio { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
