//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_O_Codes_Old
    {
        public double ID { get; set; }
        public Nullable<double> IO_code { get; set; }
        public string Description { get; set; }
        public Nullable<int> PC_I_O { get; set; }
        public Nullable<int> Replication_times { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
