//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTourism
    {
        public Nullable<double> PC_KEY { get; set; }
        public Nullable<double> VALUE { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
