//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class OccupationDistribution
    {
        public string OccupationID { get; set; }
        public Nullable<int> RIO { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public Nullable<int> OccupationIndex { get; set; }
        public Nullable<double> Percent { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
