//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalData
    {
        public Nullable<double> FipsCode { get; set; }
        public Nullable<double> RIO { get; set; }
        public Nullable<double> Inc { get; set; }
        public Nullable<double> Emp { get; set; }
        public Nullable<double> GDP { get; set; }
        public Nullable<double> Wages { get; set; }
        public Nullable<double> StateLocal { get; set; }
        public Nullable<double> Federal { get; set; }
        public Nullable<double> Insurance { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
