//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEconomicBase
    {
        public Nullable<double> Employment1 { get; set; }
        public Nullable<double> Employment2 { get; set; }
        public Nullable<double> Employment3 { get; set; }
        public Nullable<double> Employment4 { get; set; }
        public Nullable<double> Employment5 { get; set; }
        public Nullable<double> Employment6 { get; set; }
        public Nullable<double> Employment7 { get; set; }
        public Nullable<double> Employment8 { get; set; }
        public Nullable<double> Employment9 { get; set; }
        public Nullable<double> Employment10 { get; set; }
        public Nullable<double> Employment11 { get; set; }
        public Nullable<double> Income1 { get; set; }
        public Nullable<double> Income2 { get; set; }
        public Nullable<double> Income3 { get; set; }
        public Nullable<double> Income4 { get; set; }
        public Nullable<double> Income5 { get; set; }
        public Nullable<double> Income6 { get; set; }
        public Nullable<double> Income7 { get; set; }
        public Nullable<double> Income8 { get; set; }
        public Nullable<double> Income9 { get; set; }
        public Nullable<double> Income10 { get; set; }
        public Nullable<double> Income11 { get; set; }
        public Nullable<double> Gross1 { get; set; }
        public Nullable<double> Gross2 { get; set; }
        public Nullable<double> Gross3 { get; set; }
        public Nullable<double> Gross4 { get; set; }
        public Nullable<double> Gross5 { get; set; }
        public Nullable<double> Gross6 { get; set; }
        public Nullable<double> Gross7 { get; set; }
        public Nullable<double> Gross8 { get; set; }
        public Nullable<double> Gross9 { get; set; }
        public Nullable<double> Gross10 { get; set; }
        public Nullable<double> Gross11 { get; set; }
        public Nullable<double> Output1 { get; set; }
        public Nullable<double> Output2 { get; set; }
        public Nullable<double> Output3 { get; set; }
        public Nullable<double> Output4 { get; set; }
        public Nullable<double> Output5 { get; set; }
        public Nullable<double> Output6 { get; set; }
        public Nullable<double> Output7 { get; set; }
        public Nullable<double> Output8 { get; set; }
        public Nullable<double> Output9 { get; set; }
        public Nullable<double> Output10 { get; set; }
        public Nullable<double> Output11 { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
