//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndustry
    {
        public string Industry { get; set; }
        public Nullable<int> IndustryID { get; set; }
        public string Section { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<double> Employment { get; set; }
        public Nullable<double> Income { get; set; }
        public Nullable<double> GrossStateProduct { get; set; }
        public Nullable<double> Output { get; set; }
        public Nullable<int> SIC { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
