//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOccupation
    {
        public Nullable<int> OccupationIndex { get; set; }
        public string OccupationID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string DetailsName { get; set; }
        public Nullable<int> DitailsID { get; set; }
        public Nullable<double> Value { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
