//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEIaPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZNewIoCode
    {
        public int ID { get; set; }
        public Nullable<int> IO_KEY { get; set; }
        public string IO_DESC { get; set; }
        public Nullable<int> PC_KEY { get; set; }
        public Nullable<int> PC_KEY_FOUND { get; set; }
        public Nullable<int> SIC { get; set; }
    }
}
